# fly.toml app configuration file generated for gabrielacruz on 2025-02-14T22:29:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gabrielacruz'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
NODE_ENV = "production"
BASE_URL = "https://gabrielacruz.fly.dev"